//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.659, BuildCommit: 1a6cd4a9)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16.5, SDK: 16.5, Tool: ld (857.1)
//    - LC_SOURCE_VERSION: 812.107.0.0.0
//

#ifndef FBSProcess_h
#define FBSProcess_h
@import Foundation;

#include "BSDescriptionProviding-Protocol.h"
#include "FBSProcessInternal-Protocol.h"

@class BSMachPortTaskNameRight, BSProcessHandle, RBSProcessIdentity;

@interface FBSProcess : NSObject <BSDescriptionProviding, FBSProcessInternal> {
    /* instance variables */
    BSProcessHandle *_handle;
    RBSProcessIdentity *_identity;
    _Bool _running;
    BSMachPortTaskNameRight *_taskNameRight;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly, retain, nonatomic) BSProcessHandle *handle;
@property (readonly) unsigned long long hash;
@property (readonly, retain, nonatomic) RBSProcessIdentity *identity;
@property (readonly, nonatomic) int pid;
@property (readonly, nonatomic) _Bool running;
@property (readonly) Class superclass;
@property (readonly, retain, nonatomic) BSMachPortTaskNameRight *taskNameRight;

/* class methods */
+ (id)currentProcess;

/* instance methods */
- (id)_initForCurrentProcess;
- (void)_terminateWithRequest:(id)request forWatchdog:(id)watchdog;
- (_Bool)_watchdog:(id)_watchdog shouldTerminateWithDeclineReason:(out id *)reason;
- (id)_watchdog:(id)_watchdog terminationRequestForViolatedProvision:(id)provision error:(id)error;
- (void)dealloc;
- (id)description;
- (id)descriptionBuilderWithMultilinePrefix:(id)prefix;
- (id)descriptionWithMultilinePrefix:(id)prefix;
- (id)handle;
- (id)identity;
- (id)init;
- (_Bool)isRunning;
- (int)pid;
- (id)succinctDescription;
- (id)succinctDescriptionBuilder;
- (id)taskNameRight;

@end

#endif /* FBSProcess_h */