//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.659, BuildCommit: 1a6cd4a9)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 16.5, SDK: 16.5, Tool: ld (857.1)
//    - LC_SOURCE_VERSION: 812.107.0.0.0
//

#ifndef FBSScene_h
#define FBSScene_h
@import Foundation;

#include "BSDescriptionProviding-Protocol.h"
#include "FBSSceneAgentProxy-Protocol.h"
#include "FBSSceneClientAgent-Protocol.h"
#include "FBSSceneClientSettings.h"
#include "FBSSceneDefinition.h"
#include "FBSSceneHandle-Protocol.h"
#include "FBSSceneIdentity.h"
#include "FBSSceneIdentityToken.h"
#include "FBSSceneSettings.h"
#include "FBSSceneSnapshotRequestDelegate-Protocol.h"
#include "FBSSceneSpecification.h"
#include "FBSSceneUpdater-Protocol.h"
#include "FBSSceneUpdaterDelegate-Protocol.h"
#include "FBSSerialQueue.h"

@class BSAuditToken;
@protocol FBSSceneDelegate;

@interface FBSScene : NSObject <BSDescriptionProviding, FBSSceneAgentProxy, FBSSceneHandle, FBSSceneSnapshotRequestDelegate, FBSSceneUpdaterDelegate> {
    /* instance variables */
    FBSSerialQueue *_callOutQueue;
    id <FBSSceneClientAgent> _callOutQueue_agent;
    _Bool _callOutQueue_agentInvalidateCalled;
    id /* block */ _callOutQueue_agentMessageHandler;
    NSMutableArray *_callOutQueue_agentSessions;
    FBSSceneDefinition *_definition;
    _Bool _hasAgent;
    FBSSceneIdentity *_identity;
    FBSSceneIdentityToken *_identityToken;
    struct os_unfair_lock_s { unsigned int _os_unfair_lock_opaque; } _lock;
    FBSSceneClientSettings *_lock_clientSettings;
    id <FBSSceneDelegate> _lock_delegate;
    NSOrderedSet *_lock_layers;
    FBSSceneSettings *_lock_settings;
    id <FBSSceneUpdater> _lock_updater;
}

@property (readonly, nonatomic) FBSSceneClientSettings *clientSettings;
@property (readonly, copy) NSString *debugDescription;
@property (weak, nonatomic) id <FBSSceneDelegate> delegate;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly, nonatomic) BSAuditToken *hostAuditToken;
@property (readonly, copy, nonatomic) NSString *identifier;
@property (readonly, copy, nonatomic) FBSSceneIdentity *identity;
@property (readonly, nonatomic) FBSSceneIdentityToken *identityToken;
@property (readonly, nonatomic) FBSSceneSettings *settings;
@property (readonly, nonatomic) FBSSceneSpecification *specification;
@property (readonly) Class superclass;

/* instance methods */
- (void)_callOutQueue_agent_didCreateWithTransitionContext:(id)context completion:(id /* block */)completion;
- (void)_callOutQueue_agent_willDestroyWithTransitionContext:(id)context completion:(id /* block */)completion;
- (void)_callOutQueue_invalidate;
- (void)_callOutQueue_invalidateAgent;
- (void)_calloutQueue_comsumeLock_updateClientSettings:(id)settings withTransitionContext:(id)context;
- (_Bool)_hasAgent;
- (id)_initWithUpdater:(id)updater identityToken:(id)token identity:(id)identity specification:(id)specification settings:(id)settings initialClientSettings:(id)settings;
- (void)agent:(id)agent registerMessageHandler:(id /* block */)handler;
- (void)agent:(id)agent sendMessage:(id)message withResponse:(id /* block */)response;
- (void)attachContext:(id)context;
- (void)attachLayer:(id)layer;
- (void)attachSceneContext:(id)context;
- (id)callOutQueue;
- (id)clientProcess;
- (id)clientSettings;
- (void)closeSession:(id)session;
- (id)contexts;
- (id)counterpartAgent;
- (id)definition;
- (id)delegate;
- (id)description;
- (id)descriptionBuilderWithMultilinePrefix:(id)prefix;
- (id)descriptionWithMultilinePrefix:(id)prefix;
- (void)detachContext:(id)context;
- (void)detachLayer:(id)layer;
- (void)detachSceneContext:(id)context;
- (id)display;
- (id)fbsDisplay;
- (id)hostAuditToken;
- (id)hostProcess;
- (id)identifier;
- (id)identity;
- (id)identityToken;
- (id)init;
- (_Bool)invalidateSnapshotWithContext:(id)context;
- (id)layers;
- (id)openSessionWithName:(id)name executionPolicy:(id)policy;
- (id)parameters;
- (_Bool)performSnapshotWithContext:(id)context;
- (void)sendActions:(id)actions;
- (void)setDelegate:(id)delegate;
- (id)settings;
- (id)snapshotRequest;
- (_Bool)snapshotRequest:(id)request performWithContext:(id)context;
- (_Bool)snapshotRequestAllowSnapshot:(id)snapshot;
- (id)specification;
- (id)succinctDescription;
- (id)succinctDescriptionBuilder;
- (void)updateClientSettings:(id)settings withTransitionContext:(id)context;
- (void)updateClientSettingsWithBlock:(id /* block */)block;
- (void)updateClientSettingsWithTransitionBlock:(id /* block */)block;
- (void)updater:(id)updater didReceiveActions:(id)actions;
- (void)updater:(id)updater didReceiveMessage:(id)message withResponse:(id /* block */)response;
- (void)updater:(id)updater didUpdateSettings:(id)settings withDiff:(id)diff transitionContext:(id)context completion:(id /* block */)completion;

@end

#endif /* FBSScene_h */
